# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dEtBAD3fKF6FXOvn5oNTbai9YfcU4cV

5.En un club se registran de uno en uno los siguientes datos de sus socios: Documento de socio, Apellido y nombre, Edad y Tipo de deporte que practica (1 tenis, 2 rugby, 3 voley, 4 hockey, 5 futbol). Diseñar el código de un algoritmo que permita mostrar por pantalla cuantos socios practican cada deporte y el promedio de edad de los jugadores.
"""

tenis=1
rugby=1
voley=1
hockey=1
futbol=1
edaT=0
suma=0
contador=0
while tenis >= 1:
 
     ### AGREGUE ESTE CONDICIONAL 
  op=str.lower(input("Deseas ingresar un miembro: si o no ")) #con esto rompenos ciclo while
  if op == "no":
       break
  elif op== "si": # si marca si ingresa a pedir los datos
          doc=int(input("ingrese su numero de documento: ")) 
          app=input("Ingrese su apellido: ")
          nom=input("Ingrese su nombre: ")
          edd=int(input("Ingrese su edad: "))
          dep=str.upper(input("Ingrese el deporte que practica --> TENIS --> RUGBY --> VOLEY --> HOCKEY --> FUTBOL: "))
          edaT = edaT + edd # suma de edades de todos los miembros
          contador = contador + 1 #contador para promedio

  if tenis >= 1 and dep == "TENIS":
     sum=suma + tenis
     tenis += 1
     print("El numero de jugadores de tenis son: ", sum)
  
  if rugby >= 1 and dep == "RUGBY":
       sum_un= suma + rugby
       rugby += 1
       print("El numero de jugadores de rugby son: ", sum_un)
  if voley >= 1 and dep == "VOLEY":
       sum_do=suma + voley
       voley += 1
       print("El numero de jugdores de voley son: ", sum_do)
  if hockey >= 1 and dep == "HOCKEY":
       sum_tr= suma + hockey
       hockey += 1
       print("El numero de jugadores de hockey son: ", sum_tr)
  if futbol >= 1 and dep == "FUTBOL":
       sum_cu= suma + futbol
       futbol += 1
       print("El numero de jugadores de futbol son: ", sum_cu)
           
prom= edaT/ contador
print("Promedio es: ",prom)